MyBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import views
from django.views.static import serve
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('', views.index),
    path('login/', views.login),
    path('reg/', views.reg),
    path('get_verification_code/', views.get_verification_code),
    path('logout/', views.logout),
    path('blog/', include('blog.urls')),
    re_path('backstage/(?P<username>\w+)', views.backstage),
    re_path('add_article/', views.add_article),
    re_path('del_article/', views.del_article),
    re_path('edit_article/', views.edit_article),
    path('article_up_down/', views.article_up_down),
    path('comment/', views.comment),
    path('del_comment/', views.del_comment),
    path('comment_up/', views.comment_up),
    path('comment_up/', views.comment_up),
    # media 配置
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

blog/urls.py
from django.urls import path, re_path
from . import views
urlpatterns = [
    path('<str:user_site>/', views.home_site),
    path('<str:user_site>/article/<int:article_id>', views.article_detail),
    re_path('(?P<user_site>\w+)/(?P<condition>homecategory|tag|date)/(?P<para>(\w|-|%|:| )+)', views.home_site),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class ArticleManager(models.Manager):
    """文章按照日期归档"""

    def archive(self, **kwargs):
        archive_list = []
        articles_time = self.filter(**kwargs).order_by('create_time').values_list('create_time')
        tmp_time_list = []
        for i in articles_time:
            time = i[0].strftime('%Y-%m-%d %H')
            if time not in tmp_time_list:
                count = Article.objects.filter(create_time__icontains=time).count()
                archive_list.append((time, count))
                tmp_time_list.append(time)
        return archive_list


class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(verbose_name='手机号码', max_length=11, null=True, unique=True)
    avatar = models.FileField(verbose_name='头像', upload_to='avatar/', default="/avatar/default.jpg")
    create_time = models.DateField(verbose_name='创建时间', auto_now_add=True)
    blog = models.OneToOneField(verbose_name='个人博客', to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)
    fans = models.ManyToManyField(verbose_name='粉丝们', to='UserInfo', through='UserFans',
                                  through_fields=('user', 'follower'))

    def __str__(self):
        return self.username


class UserFans(models.Model):
    """互粉关系表，用户表多对多用户表"""
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users',
                             on_delete=models.CASCADE)
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers',
                                 on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class HomeCategory(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    read_count = models.IntegerField(verbose_name='阅读数', default=0)
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    up_count = models.IntegerField(verbose_name='点赞数', default=0)
    down_count = models.IntegerField(verbose_name='踩灭数', default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    homeCategory = models.ForeignKey(verbose_name='博主个人文章类型', to='HomeCategory', to_field='nid', null=True,
                                     on_delete=models.CASCADE)
    siteSubCategory = models.ForeignKey(verbose_name='网站子类型', to='SiteSubCategory', to_field='nid', null=True,
                                        on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )
    objects = ArticleManager()

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid', on_delete=models.CASCADE)


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(verbose_name='点赞数', default=0)
    parent_comment = models.ForeignKey(verbose_name='父级评论', to='self', null=True, default=None, on_delete=models.CASCADE)


class ArticleUpDown(models.Model):
    """
    文章点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='点赞者', to='UserInfo', to_field='nid', null=False, on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', null=False, on_delete=models.CASCADE)
    is_up = models.BooleanField(verbose_name='是否赞', default=True)

    class Meta:
        unique_together = [
            ('article', 'user', 'is_up'),
        ]

    def __str__(self):
        return str(self.is_up)


class CommentUp(models.Model):
    """
    评论点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='点赞者', to='UserInfo', to_field='nid', null=False, on_delete=models.CASCADE)
    comment = models.ForeignKey(verbose_name='评论', to="Comment", to_field='nid', null=False, on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('comment', 'user'),
        ]


class SiteCategory(models.Model):
    """网站分类表"""
    nid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='网站分类名', max_length=32, unique=True)

    def __str__(self):
        return self.name


class SiteSubCategory(models.Model):
    """网站子分类表"""
    nid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='网站子分类名', max_length=32, unique=True)
    siteCategory = models.ForeignKey("SiteCategory", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
import re
from blog import models

class RegForm(forms.Form):
    def __init__(self, request, *args, **kwargs):
        super(RegForm, self).__init__(*args, **kwargs)
        self.request = request

    username = forms.CharField(min_length=4,max_length=16,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password = forms.CharField(min_length=4,max_length=16,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    confirm_pwd = forms.CharField(min_length=4,max_length=16,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm_pwd'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}))
    nickname = forms.CharField(max_length=16,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Nickname'}))
    verification_code = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Verification_code'}))

    def clean_verification_code(self):
        if self.request.session.get('verification_code').upper() == self.cleaned_data['verification_code'].upper():
            return self.cleaned_data['verification_code']
        else:
            raise ValidationError('验证码错误!')

    def clean_username(self):
        res = re.search(r'^[a-zA-Z0-9_-]{4,16}$', self.cleaned_data['username'])
        if res:
            #用户名重复验证
            user = models.UserInfo.objects.filter(username=self.cleaned_data['username']).first()
            if not user:
                return self.cleaned_data['username']
            else:
                raise ValidationError('用户名已存在!')
        else:
            raise ValidationError('用户名必须是（字母，数字，下划线，减号）组成的4到16位!')


    def clean(self):
        if self.cleaned_data.get('password') == self.cleaned_data.get('confirm_pwd'):
            return self.cleaned_data
        else:
            raise ValidationError('密码不一致!')

templates/add_article.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.css' %}">
    <style>
        .container {
            margin-top: 10px;
        }
    </style>
    <title>添加文章</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <form class="" action="/add_article/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" placeholder="title" name="title">
                </div>

                <div class="form-group">
                    <label for="desc">文章描述</label>
                    <input type="text" class="form-control" id="desc" placeholder="desc" name="desc">
                </div>

                <div class="form-group">
                    <label class="required" for="id_homeCategory">博主个人文章类型:</label>
                    <select class="form-control" name="homeCategory" id="id_homeCategory" required="">
                        <option value="">---------</option>
                        {% for homeCategory in homeCategory_list %}
                            <option value="{{ homeCategory.nid }}">{{ homeCategory.title }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label class="required" for="id_siteSubCategory">网站子类型:</label>
                    <select class="form-control" name="siteSubCategory" id="id_siteSubCategory" required="">
                        <option value="">---------</option>
                        {% for siteSubCategory in siteSubCategory_list %}
                            <option value="{{ siteSubCategory.nid }}">{{ siteSubCategory.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <label class="required" for="id_tag">标签:</label>
                {% for tag in tag_list %}
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="id_tag" name="tag" value="{{ tag.nid }}">
                            {{ tag.title }}
                        </label>
                    </div>
                {% endfor %}

                <label class="required" for="article_content">文章内容:</label>
                <textarea class="form-control" id="article_content" name="article_content" cols="80"
                          rows="15"></textarea>

                <button type="submit" class="btn btn-default">Submit</button>

            </form>

            {{ error_msg }}
        </div>
    </div>
</div>
<script src="{% static 'kindeditor/kindeditor-all.js' %}"></script>
<script src="{% static 'bs/js/jquery-1.12.4.js' %}"></script>
<script>
                $(function () {
                    initKindEditor();
                });

                function initKindEditor() {
                    var kind = KindEditor.create('#article_content', {
                        width: '100%',       // 文本框宽度(可以百分比或像素)
                        height: '300px',     // 文本框高度(只能像素)
                        minWidth: 200,       // 最小宽度（数字）
                        minHeight: 400,      // 最小高度（数字）
                        uploadJson: '/kind/upload_img/',
                        extraFileUploadParams: {
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        fileManagerJson: '/kind/file_manager/',
                        allowPreviewEmoticons: true,
                        allowImageUpload: true
                    });
                }
            </script>
</body>
</html>

templates/backstage_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.css' %} "/>
    {% block link %}
    {% endblock %}
    <style>
        *{
            overflow: auto;
        }
        .top {
            background-color: #122b40;
            position: fixed;
            top: 0;
            right: 0;
            left: 0;
            height: 70px;
            line-height: 70px;
        }
        .top .logo{
            color: #eeeeee;
            font-size: 25px;
            font-weight: bold;
            padding-left: 100px;
        }
        .top .top-nav a,
        .top .top-nav span {
            color: #aaa;
            margin: 0 15px;
        }
        .top .top-nav #user{
            color: white;
        }
        .cont_lt {
            position: fixed;
            top: 70px;
            left: 0;
            bottom: 0;
            width: 270px;
            border-right: 1px solid #122b40;
        }
        .cont_rt {
            position: fixed;
            top: 70px;
            right: 0;
            bottom: 0;
            left: 270px;
        }

    </style>
    {% block title %}
        <title></title>
    {% endblock %}
</head>
<body>
<div class="row">
    <div class="top">
        <div class="col-md-2">
            <div class="logo">后台管理</div>
        </div>
        <div class="top-nav col-md-6 col-md-offset-1">
            <a href="/">首页</a>
        </div>
        <div class="top-nav col-md-3">
            <span>欢迎你<span id="user">{{ user }}</span></span>
            <a href="/logout/">注销</a>
            <a href="#">修改密码</a>
        </div>
    </div>
</div>
<div class="cont_lt">
    {% block cont_lt %}
    {% endblock %}
</div>
<div class="cont_rt">
    {% block cont_rt %}
    {% endblock %}
</div>
<script src="{% static 'bs/js/jquery-1.12.4.js' %}"></script>
<script src="{% static 'bs/js/bootstrap.js' %}"></script>
<script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title></title>
</head>
<body>
<!-- 导航条开始 -->
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% for type_choice in func %}
                    <li><a href="#">{{ type_choice.1 }}</a></li>
                {% endfor %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="/backstage/{{ request.user.username }}">{{ request.user }}</a></li>
                    <li><a href="/logout/">注销</a></li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">设置 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- 导航条结束 -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">网站分类</div>
                <!-- List group -->
                <ul class="list-group">
                    {% for siteCategory in siteCategory_list %}
                        <li class="list-group-item cate">{{ siteCategory.name }}</li>
                        {% for siteSubCategory in siteCategory.sitesubcategory_set.all %}
                            <li class="list-group-item siteSubCategory">{{ siteSubCategory.name }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-md-7">
            {% csrf_token %}
            <div class="article_list">
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-info">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'bs/js/jquery-1.12.4.js' %}"></script>
<script src="{% static 'bs/js/bootstrap.js' %}"></script>
<script>
    String.prototype.format = function () {
        var args = arguments;
        return this.replace(/\{(\d+)\}/g, function (s, i) {
            return args[i];
        })
    };
    function Load_article(article_list) {
        /*加载文章表格*/
        var html = "";
        $.each(article_list, function (k, v) {
            var article_item_str = "<div class='article_item'>";
            var title_str = "<h5><a class='art_title' href='/blog/{0}/article/{1}'>{2}</a></h5>".format(v['user__blog__site'], v['nid'], v['title']);
            var avatar_desc_row_str = "<div class='row'><div class='avatar_img col-md-1'><a href='/blog/{0}'><img src='/media/{1}' alt='' width='60' height='60'/></a></div><div class='desc col-md-10'>{2}</div></div>".format(v['user__blog__site'], v['user__avatar'], v['desc']);
            var info_row_str = "<div class='info'><a class='username' href='/blog/{0}'>{1}</a><span class='timer'>发布于{2}</span>&nbsp;&nbsp;<a href=''><span class='glyphicon glyphicon-comment'></span>&nbsp;<span>评论({3})</span></a><a href=''><span class='glyphicon glyphicon-eye-open'></span>&nbsp;<span>阅读({4})</span></a><a class='poll' article_id='{5}' href='###'><span class='glyphicon glyphicon-thumbs-up'></span>&nbsp;<span>赞(<span class='poll_num_{6}'>{7}</span>)</span></a><a href=''><span class='glyphicon glyphicon-thumbs-down'></span>&nbsp;<span>踩({8})</span></a><div class='errors_{9}'></div><div class='errors'></div></div>".format(v['user__blog__site'], v['user__nickname'], v['create_time'], v['comment_count'], v['read_count'], v['nid'], v['nid'], v['up_count'], v['down_count'], v['nid']);
            article_item_str = article_item_str + title_str + avatar_desc_row_str + info_row_str + "</div><hr>";
            html += article_item_str;
        });
        return html;
    }
    function Load_pagination(page, article_num_pages) {
        page = parseInt(page);
        article_num_pages = parseInt(article_num_pages);
        var pagination_str = "<ul class='pagination'>";
        var article_has_previous_li = "<li class='disabled'><a href='###'>上一页</a></li>";
        if ((page - 1) > 0) {
            article_has_previous_li = "<li class=''><a href='###' page='{0}'>上一页</a></li>".format(page - 1);
        }
        var article_has_next_li = "<li class='disabled'><a href='###'>下一页</a></li>";
        if (page < article_num_pages) {
            article_has_next_li = "<li class=''><a href='###' page='{0}'>下一页</a></li>".format(page + 1);
        }
        var article_page_range_li = "";
        for (var i = 1; i <= article_num_pages; i++) {
            if (i == page) {
                article_page_range_li += "<li class='active'><a id='cur_page_a_tag' page='{0}' href='###'>{1}</a></li>".format(i, i);
            } else if (i < 3 || i > article_num_pages - 2) {
                article_page_range_li += "<li><a page='{0}' href='###'>{1}</a></li>".format(i, i);
            } else if (i <= (page + 1) && i >= (page - 1)) {
                article_page_range_li += "<li><a page='{0}' href='###'>{1}</a></li>".format(i, i);
            } else if (i == page + 2 || i == page - 2) {
                article_page_range_li += "<li><span>. . .</span></li>";
            }
        }
        pagination_str = pagination_str + article_has_previous_li + article_page_range_li + article_has_next_li + "</ul>";
        return pagination_str;
    }
    /*更新文章内容*/
    $('.article_list').delegate('a', 'click', function () {
        var page = $(this).attr('page');
        if (page) {
            $.ajax({
                url: '',
                type: 'GET',
                data: {
                    'page': page
                },
                success: function (data) {
                    console.log(data);
                    data = JSON.parse(data);
                    var article_item_str = Load_article(data['article_list']);
                    var pagination_str = Load_pagination(data['page'], data['article_num_pages']);
                    $('.article_list').html('');
                    $('.article_list').append(article_item_str);
                    $('.article_list').append(pagination_str);
                }
            });
        }
    });
    $(function () {
        var csrf = $("[name='csrfmiddlewaretoken']").val();
        $.ajax({
            url: '',
            type: 'POST',
            data: {
                'csrfmiddlewaretoken': csrf
            },
            success: function (data) {
                data = JSON.parse(data);
                var article_item_str = Load_article(data['article_list']);
                var pagination_str = Load_pagination(data['page'], data['article_num_pages']);
                $('.article_list').html('');
                $('.article_list').append(article_item_str);
                $('.article_list').append(pagination_str);
            }
        });
    });
    $('.article_list').delegate('.poll', 'click', function () {
        var csrf = $("[name='csrfmiddlewaretoken']").val();
        var article_id = $(this).attr('article_id');
        {% if request.user.is_authenticated %}
            $.ajax({
                url: "/article_up_down/",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': csrf,
                    'article_id': article_id,
                    'is_up': true
                },
                success: function (data) {
                    data = JSON.parse(data);
                    if (data['result'] == 'success') {
                        console.log($('.poll_num_' + article_id)[0]);
                        $('.poll_num_' + article_id).text(data['up_count']);
                    } else if (data['result'] == 'is_exist') {
                        $('.errors_' + article_id).text('您已经推荐过').css({'color': 'red'});
                    } else if (data['result'] == 'fail') {
                        $('.errors_' + article_id).text('程序错误，请联系管理员').css({'color': 'red'});
                    }
                }
            });
        {% else %}
            var next_path = '{{ request.path }}';
            $(this).siblings('.errors').html('请先<a href="/login/?next_path=' + next_path + '">登录</a>').css({'color': 'red'});
        {% endif %}
    });
</script>
</body>
</html>

templates/reg.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reg.css' %}">

    <title>注册</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">用户名</label>
                    {{ reg_form.username }}
                    <span class="error_user"></span>
                </div>
                <div class="form-group">
                    <label for="id_password">密码</label>
                    {{ reg_form.password }}
                    <span class="error_password"></span>
                </div>
                <div class="form-group">
                    <label for="id_confirm_pwd">确认密码</label>
                    {{ reg_form.confirm_pwd }}
                    <span class="error_confirm_pwd"></span>
                </div>
                <div class="form-group">
                    <label for="id_email">邮箱</label>
                    {{ reg_form.email }}
                    <span class="error_email"></span>
                </div>
                <div class="form-group">
                    <label for="id_nickname">昵称</label>
                    {{ reg_form.nickname }}
                    <span class="error_nickname"></span>
                </div>
                <div class="form-group form-avatar">
                    <label for="id_avatar">头像</label>
                    <img src="/media/avatar/default.jpg" alt="" id="img_avatar">
                    <input type="file" id="id_avatar">
                    <span class="error_avatar"></span>
                </div>
                <div class="form-group">
                    <label for="id_verification_code">验证码</label>
                    <div class="row">
                        <div class="col-md-7">
                            {{ reg_form.verification_code }}
                            <span class="error_verification_code"></span>
                        </div>
                        <div class="col-md-5">
                            <img class="v_code" src="/get_verification_code/" alt="验证码" width="120" height="30"/>
                            <a class="refresh">刷新</a>
                        </div>
                    </div>
                </div>
                <input id="reg" type="button" class="btn btn-default" value="注册">
            </form>
        </div>
    </div>
</div>
<script src="{% static 'bs/js/jquery-1.12.4.js' %}"></script>
<script>
    $('#id_avatar').change(function () {
        var file = this.files[0];   //文件对象
        var fr = new FileReader();
        fr.readAsDataURL(file);
        fr.onload = function(){
            $('#img_avatar')[0].src = fr.result;
        };
    });

    $('.refresh').click(function () {
        $('.v_code')[0].src += '?';
    });
    $('#reg').click(function(){
        $('form span').text('');
        var formData = new FormData();
        var username=$("#id_username").val();
        var password=$("#id_password").val();
        var confirm_pwd=$("#id_confirm_pwd").val();
        var email=$("#id_email").val();
        var nickname=$("#id_nickname").val();
        var verification_code=$("#id_verification_code").val();
        var csrf=$("[name='csrfmiddlewaretoken']").val();
        formData.append('username', username);
        formData.append('password', password);
        formData.append('confirm_pwd', confirm_pwd);
        formData.append('email', email);
        formData.append('nickname', nickname);
        formData.append('verification_code', verification_code);
        formData.append('csrfmiddlewaretoken', csrf);
        formData.append('img_avatar', $('#id_avatar')[0].files[0]);
        $.ajax({
            url:'/reg/',
            type:'POST',
            data:formData,
            processData: false,      // 使用formdata,processData,contentType必须设为false
            contentType: false,
            success:function(data){
                data = JSON.parse(data);
                if(data['flag']){
                    location.href = '/login/';
                } else {
                    console.log(data);
                    var errors_dict = data['errors'];
                    $('.error_confirm_pwd').text(data['errors']['__all__']).css({'color':'red'});
                    for(var k in errors_dict){
                        $('#id_'+k).next().text(errors_dict[k]).css({'color':'red'});
                    }
                }
            }
        })
    });
</script>
</body>
</html>